services:
  - type: web
    name: imposter-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7937109669:AAGfK5QxLs1txa0sTk-SLKGmOqHWTWXLlfE
    plan: free
    region: frankfurt
