services:
  - type: web
    name: imposter-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        value: <DEIN_TOKEN_HIER>
      - key: RENDER_EXTERNAL_URL
        value: <DEINE_URL_HIER>
    plan: free
    region: frankfurt
