services:
  - type: worker
    name: imposter-bot
    env: python
    buildCommand: ""
    startCommand: bash start.sh
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN_HERE
